name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Emscripten
        uses: Anadian/setup-emscripten@v1
        with:
          version: latest # Specify the Emscripten version you need

      - name: Build using Makefile and EMCC
        run: |
          make

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
